---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: admin
      admin_password: admin
  ingress:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: "self-signed"
    spec:
      ingressClassName: nginx
      tls:
      - hosts:
          - grafana.mh.com
        secretName: grafana-tls
      rules:
        - host: grafana.mh.com
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
