alloy:
  clustering:
    enabled: false
    name: ""
    portName: http
  configMap:
    content: ""
    create: true
    key: null
    name: null
  enableReporting: true
  envFrom: []
  extraArgs: []
  extraEnv: []
  extraPorts: []
  hostAliases: []
  lifecycle: {}
  listenAddr: 0.0.0.0
  listenPort: 12345
  listenScheme: HTTP
  mounts:
    dockercontainers: false
    extra: []
    varlog: false
  resources: {}
  securityContext: {}
  stabilityLevel: generally-available
  storagePath: /tmp/alloy
  uiPathPrefix: /
configReloader:
  customArgs: []
  enabled: true
  image:
    digest: ""
    registry: ghcr.io
    repository: jimmidyson/configmap-reload
    tag: v0.12.0
  resources:
    requests:
      cpu: 1m
      memory: 5Mi
  securityContext: {}
controller:
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 5
    minReplicas: 1
    scaleDown:
      policies: []
      selectPolicy: Max
      stabilizationWindowSeconds: 300
    scaleUp:
      policies: []
      selectPolicy: Max
      stabilizationWindowSeconds: 0
    targetCPUUtilizationPercentage: 0
    targetMemoryUtilizationPercentage: 80
  dnsPolicy: ClusterFirst
  enableStatefulSetAutoDeletePVC: false
  extraAnnotations: {}
  extraContainers: []
  hostNetwork: false
  hostPID: false
  initContainers: []
  nodeSelector: {}
  parallelRollout: true
  podAnnotations: {}
  podDisruptionBudget:
    enabled: false
    maxUnavailable: null
    minAvailable: null
  podLabels: {}
  priorityClassName: ""
  replicas: 1
  terminationGracePeriodSeconds: null
  tolerations: []
  topologySpreadConstraints: []
  type: daemonset
  updateStrategy: {}
  volumeClaimTemplates: []
  volumes:
    extra: []
crds:
  create: true
  global:
    image:
      pullSecrets: []
      registry: ""
    podSecurityContext: {}
fullnameOverride: null
global:
  image:
    pullSecrets: []
    registry: ""
  podSecurityContext: {}
image:
  digest: null
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: grafana/alloy
  tag: null
ingress:
  annotations: {}
  enabled: false
  extraPaths: []
  faroPort: 12347
  hosts:
  - chart-example.local
  labels: {}
  path: /
  pathType: Prefix
  tls: []
nameOverride: null
rbac:
  create: true
service:
  annotations: {}
  clusterIP: ""
  enabled: true
  internalTrafficPolicy: Cluster
  nodePort: 31128
  type: ClusterIP
serviceAccount:
  additionalLabels: {}
  annotations: {}
  create: true
  name: null
serviceMonitor:
  additionalLabels: {}
  enabled: false
  interval: ""
  metricRelabelings: []
  relabelings: []
  tlsConfig: {}
