apiVersion: v1
kind: Service
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    k8s-app: kube-proxy
spec:
  type: ClusterIP
  selector:
    k8s-app: kube-proxy
  ports:
  - name: kube-proxy
    protocol: TCP
    port: 80
    targetPort: 10249
