---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: "alloy"
    targetRevision: 0.10.1
    helm:
      valueFiles:
      - $values/alloy/values.yaml
      ignoreMissingValueFiles: true
  - repoURL: https://github.com/naivary/k8s-argocd
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: alloy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
