---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: customer
  source:
    repoURL: https://github.com/naivary/k8s-argocd
    path: nginx
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
