---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
    path: deploy/kubernetes/csi-snapshotter
    targetRevision: HEAD
  - repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
    path: deploy/kubernetes/snapshot-controller
    targetRevision: HEAD
  - repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
    path: client/config/crd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: snapshot-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
