---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trident
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://netapp.github.io/trident-helm-chart
    chart: trident-operator
    targetRevision: 100.2410.0
    helm:
      valueFiles:
      - $values/trident/values.yaml
      ignoreMissingValueFiles: true
  - repoURL: https://github.com/naivary/k8s-argocd
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: trident-system
  ignoreDifferences:
    - group: apiextensions.k8s.io
      jqPathExpressions:
      - .spec.versions[]? | .additionalPrinterColumns[]? | .priority
      kind: CustomResourceDefinition
      name: tridentconfigurators.trident.netapp.io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
