apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-object-storage
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: loki
  objectStoreNamespace: rook-ceph
