apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    exporter: node
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 9100
    protocol: TCP
    targetPort: https
  selector:
    exporter: node
