apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: dns-config-injection
spec:
  rules:
    - name: dns-config-injection
      context:
      - name: corednsServiceClusterIP
        apiCall:
          urlPath: "/api/v1/namespaces/kube-system/services/coredns"
          jmesPath: "spec.clusterIP"
      match:
        any:
        - resources:
            kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          spec:
            dnsPolicy: None
            dnsConfig:
              nameservers:
              - "{{ corednsServiceClusterIP }}"
              searches:
              - "{{ request.namespace }}.svc.cluster.local"
              - svc.cluster.local
              - cluster.local
              - default.svc.cluster.local
              - fritz.box
              options:
              - name: ndots
                value: "5"


