apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-query
  namespace: monitoring
spec:
  ingressClassName: "nginx"
  rules:
  - http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: loki-gateway
           port:
             name: http-metrics
