apiVersion: v1
kind: Service
metadata:
  name: receiver-store-1
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  ports:
    - port: 10907
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: receiver
    app.kubernetes.io/instance: receiver-1
