kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-only
subjects:
- kind: ServiceAccount
  name: argocd-manager
  namespace: t1-argocd
roleRef:
  kind: ClusterRole
  name: read-only
  apiGroup: "rbac.authorization.k8s.io"
