apiVersion: v1
kind: Service
metadata:
  name: alloy-tracing
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: tracing
    port: 4317
    protocol: TCP
    targetPort: 4317
  selector:
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/name: alloy
