apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    k8s-app: kube-scheduler
spec:
  type: ClusterIP
  selector:
    component: kube-scheduler
  ports:
  - name: kube-scheduler
    protocol: TCP
    port: 80
    targetPort: 10259

