apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
  namespace: kube-system
  labels:
    k8s-app: kube-apiserver
spec:
  type: ClusterIP
  selector:
    component: kube-apiserver
  ports:
  - name: kube-apiserver
    protocol: TCP
    port: 80
    targetPort: 6443
