---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: compactor
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
