apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  project: default
  sources:
  - repoURL: https://charts.gitlab.io/
    chart: gitlab
    targetRevision: 9.5.0
    helm:
      valueFiles:
      - $values/gitlab/values.yaml
  - repoURL: 'https://github.com/naivary/k8s-configs.git'
    targetRevision: main
    ref: values
