apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespacer
  namespace: argo-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacer
rules:
- apiGroups: [""] 
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespacer
subjects:
- kind: ServiceAccount
  name: namespacer
  namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole 
  name: cluster-admin
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: namespacer
  namespace: argo-events
spec:
  eventBusName: "jetstream"
  template:
    serviceAccountName: namespacer
  resource:
    namespace-creation:
      group: "" 
      version: v1
      resource: namespaces
      eventTypes:
        - ADD
      filter:
        afterStart: true
