---
apiVersion: v1
kind: Secret
metadata:
  name: hashring
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  hashring.json: |-
    [
        {
            "endpoints": [
                "receiver-store-1.monitoring.svc.cluster.local:10907",
                "receiver-store-2.monitoring.svc.cluster.local:10907"
            ]
        }
    ]
