apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana/alloy
    targetRevision: 1.4.0
    helm:
      valueFiles:
      - $values/alloy/values.yaml
  - repoURL: 'https://github.com/naivary/k8s-configs.git'
    targetRevision: main
    ref: values
