apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    automated:
      enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  project: default
  sources:
  - repoURL: https://charts.gitlab.io/
    chart: gitlab
    targetRevision: 9.5.0
    helm:
      parameters:
        - name: "upgradeCheck.enabled"
          value: "false"
      valueFiles:
      - $values/gitlab/values.yaml
  - repoURL: 'https://github.com/naivary/k8s-configs.git'
    targetRevision: main
    ref: values
