apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana/grafana
    targetRevision: 10.1.2
    helm:
      valueFiles:
      - $values/grafana-operator/values.yaml
  - repoURL: 'https://github.com/naivary/k8s-configs.git'
    targetRevision: main
    ref: values
