apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
  - repoURL: 'https://github.com/naivary/k8s-configs.git'
    targetRevision: HEAD
    path: observability/thanos/2
    recursive: true
