---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaAlertRuleGroup
metadata:
  name: node-exporter-disk-pressure
  namespace: monitoring
spec:
  folderRef: alerts
  instanceSelector:
    matchLabels:
      dashboard: "grafana"
  interval: 5m
  rules:
    - uid: node_disk_pressure
      for: 0s
      title: Disk Usage - 80%
      condition: C
      data:
        - refId: A
          relativeTimeRange:
            from: 600
            to: 0
          datasourceUid: "thanos" 
          model:
            expr: 'node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}'
            range: true
            intervalMs: 1000
            refId: A
            editorMode: code
            format: time-series
            datasource:
                type: prometheus
                uid: "thanos"
        - refId: B
          datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params: []
                  type: gt
                operator:
                  type: and
                query:
                  params:
                      - B
                reducer:
                  params: []
                  type: last
                type: query
            datasource:
                type: __expr__
                uid: __expr__
            expression: A
            intervalMs: 1000
            maxDataPoints: 43200
            reducer: last
            refId: B
            type: reduce
        - refId: C
          datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params:
                      - 0.2
                  type: lt
                operator:
                  type: and
                query:
                  params:
                      - C
                reducer:
                  params: []
                  type: last
                type: query
            datasource:
                type: __expr__
                uid: __expr__
            expression: B
            intervalMs: 1000
            maxDataPoints: 43200
            refId: C
            type: threshold
      noDataState: NoData
      execErrState: Error
      labels:
        severity: high
        team: kubernetes-ops
