---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaNotificationPolicy
metadata:
  name: test
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboard: "grafana"
  route:
    receiver: grafana-default-email
    group_by:
      - grafana_folder
      - alertname
    routes:
      - receiver: operations-team
        object_matchers:
          - - team
            - =
            - kubernetes-ops
        routes:
          - object_matchers:
              - - severity
                - =
                - high
            repeat_interval: 5m
