---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: <example-email>
    server: https://acme-v02.api.letsencrypt.org/directory 
    privateKeySecretRef:
      name: acme-issuer-private-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx

